server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.72.183.76:3306/secondtrading
    username: root
    password: 0.
mybatis-plus:
  type-aliases-package: com.campus.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl